import Head from "next/head"
import Image from "next/image"
import styles from "../styles"
import { Navbar } from "../components"

export default function Home() {
  return (
    <div className="bg-indigo-300 w-full">
      <Head>
        <title>CANIMMVN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="w-full h-[1800px]"></div>
    </div>
  )
}
